//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOCCounter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOCCounter.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string resAbout {
            get {
                return ResourceManager.GetString("resAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and remove file extensions....
        /// </summary>
        internal static string resAddRemoveExt {
            get {
                return ResourceManager.GetString("resAddRemoveExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string resApply {
            get {
                return ResourceManager.GetString("resApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        internal static string resBlank {
            get {
                return ResourceManager.GetString("resBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string resBrowse {
            get {
                return ResourceManager.GetString("resBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Browse....
        /// </summary>
        internal static string resBrowseElipsis {
            get {
                return ResourceManager.GetString("resBrowseElipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string resCancel {
            get {
                return ResourceManager.GetString("resCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string resComments {
            get {
                return ResourceManager.GetString("resComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Contents.
        /// </summary>
        internal static string resContents {
            get {
                return ResourceManager.GetString("resContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count LOC in and under this folder:.
        /// </summary>
        internal static string resCountFolder {
            get {
                return ResourceManager.GetString("resCountFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Lines.
        /// </summary>
        internal static string resCountLines {
            get {
                return ResourceManager.GetString("resCountLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Count Lines.
        /// </summary>
        internal static string resCountLOC {
            get {
                return ResourceManager.GetString("resCountLOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string resDirectory {
            get {
                return ResourceManager.GetString("resDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string resExit {
            get {
                return ResourceManager.GetString("resExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions.
        /// </summary>
        internal static string resExtensions {
            get {
                return ResourceManager.GetString("resExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        internal static string resExtFormDeselectAll {
            get {
                return ResourceManager.GetString("resExtFormDeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extensions to be processed:.
        /// </summary>
        internal static string resExtFormHeader {
            get {
                return ResourceManager.GetString("resExtFormHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string resExtFormSelectAll {
            get {
                return ResourceManager.GetString("resExtFormSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string resFile {
            get {
                return ResourceManager.GetString("resFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string resFileName {
            get {
                return ResourceManager.GetString("resFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        internal static string resFileType {
            get {
                return ResourceManager.GetString("resFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string resHelp {
            get {
                return ResourceManager.GetString("resHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCCounter.exe, Sloc.dll and LOCCounter.exe.config should all be in the same folder..
        /// </summary>
        internal static string resHelp00 {
            get {
                return ResourceManager.GetString("resHelp00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A blank line contains only white space. A comment line begins with a comment delimiter or is a line between comment delimiters (according to the file extension as defined in CommentDelimiters.xml). A line that begins as a comment but contains code is considered to be a comment, e.g.,.
        /// </summary>
        internal static string resHelp01 {
            get {
                return ResourceManager.GetString("resHelp01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* cmnt */ x = 1;.
        /// </summary>
        internal static string resHelp02 {
            get {
                return ResourceManager.GetString("resHelp02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A line that begins with code but contains a comment is considered to be code. Lines that are not blank and not commented are considered Source Lines of Code (SLOC). A line that begins with code and then (on the same line) starts (but does not terminate) a multi-line comment will cause incorrect results, e.g.,.
        /// </summary>
        internal static string resHelp03 {
            get {
                return ResourceManager.GetString("resHelp03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x = 1; /* Start comment.
        /// </summary>
        internal static string resHelp04 {
            get {
                return ResourceManager.GetString("resHelp04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    this counted as code because previous line starts with code..
        /// </summary>
        internal static string resHelp05 {
            get {
                return ResourceManager.GetString("resHelp05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program first collects the list of files in and under a root folder with any extension in the selectable list. LOCCounter.exe.config may be modified to handle more file types. For unknown file types, the program assumes that comments are delimited as with the C programming language (//, /*, */)..
        /// </summary>
        internal static string resHelp06 {
            get {
                return ResourceManager.GetString("resHelp06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML files may use comments to hide embedded javascript from non-compliant browsers. Those script lines will be treated as comments..
        /// </summary>
        internal static string resHelp07 {
            get {
                return ResourceManager.GetString("resHelp07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance can be slow for files with tens of thousands of lines, so if you have folders full of huge XML data files, you could see long execution times. Try removing some of the file extensions from the list. The Cancel button is generally ineffective while the program first begins to collect the list of files. If your source tree is very large, the collection process can take a while..
        /// </summary>
        internal static string resHelp08 {
            get {
                return ResourceManager.GetString("resHelp08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once a directory has been counted, a file can be opened in Notepad by clicking with the right mouse button..
        /// </summary>
        internal static string resHelp09 {
            get {
                return ResourceManager.GetString("resHelp09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view the subtotals for a group of files, select any items in the list with the left mouse button, then use the right mouse button with the menu command. To view the subtotals for an extension, first sort the File Type column to make it easy to select the files. Use CTRL-C to copy the contents of the popup window to the clipboard..
        /// </summary>
        internal static string resHelp10 {
            get {
                return ResourceManager.GetString("resHelp10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A &apos;feature&apos; of Windows is that files with extensions longer than 3 characters have a short 8.3 name with an extension that has three characters. For example, when processing HTM files, HTML files may also be processed. This program does not correct for that..
        /// </summary>
        internal static string resHelp11 {
            get {
                return ResourceManager.GetString("resHelp11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;LOCCounterStd.exe /?&apos; at the command line to see command line options..
        /// </summary>
        internal static string resHelp12 {
            get {
                return ResourceManager.GetString("resHelp12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string resLines {
            get {
                return ResourceManager.GetString("resLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source LOC.
        /// </summary>
        internal static string resSourceLOC {
            get {
                return ResourceManager.GetString("resSourceLOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use   LOCCounterStd.exe   to send output to a file..
        /// </summary>
        internal static string resUseStd {
            get {
                return ResourceManager.GetString("resUseStd", resourceCulture);
            }
        }
    }
}
